services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: radualexia2515
      POSTGRES_DB: Restaurant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:radualexia2515@db:5432/Restaurant
    env_file:
      - .env

  frontend:
    build: ./restaurant-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env
  
volumes:
  db_data: